package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;

public class MainWindow extends javax.swing.JFrame {
    
    Color base = new Color(20,23,31);
    Color focus = new Color(55, 58, 64);
    
    boolean firstButton = true;
    boolean secondButton = false;
    public boolean thirdButton = false;
    boolean fourthButton = false;
    public boolean fifthButton = false;
    
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    public void turnAllFalse() {
        firstButton = false;
        secondButton = false;
        thirdButton = false;
        fourthButton = false;
        fifthButton = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBarra = new javax.swing.JPanel();
        try(InputStream is = getClass().getResourceAsStream("/assets/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 14f);
            jlblHomeIcon = new javax.swing.JLabel();
            jlblHomeIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jbtnPrimero = new javax.swing.JButton();
        jbtnQuinto = new javax.swing.JButton();
        jbtnTercero = new javax.swing.JButton();
        jbtnCuarto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSegundo = new javax.swing.JButton();
        try(InputStream is = getClass().getResourceAsStream("/assets/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 14f);
            jlblVentaIcon = new javax.swing.JLabel();
            jlblVentaIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        try(InputStream is = getClass().getResourceAsStream("/assets/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 14f);
            jlblRepuestosIcon = new javax.swing.JLabel();
            jlblRepuestosIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        try(InputStream is = getClass().getResourceAsStream("/assets/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 14f);
            jlblReporteIcon = new javax.swing.JLabel();
            jlblReporteIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        try(InputStream is = getClass().getResourceAsStream("/assets/Font Awesome 6 Free-Solid-900.otf")){
            Font fontAwesome = Font.createFont(Font.TRUETYPE_FONT, is);
            fontAwesome = fontAwesome.deriveFont(Font.PLAIN, 14f);
            jlblClientesIcon = new javax.swing.JLabel();
            jlblClientesIcon.setFont(fontAwesome);
        }catch (IOException | FontFormatException exp) {
            exp.printStackTrace();
        }
        jlblNombreAdministrador = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlBarra.setBackground(new java.awt.Color(20, 23, 31));
        jpnlBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblHomeIcon.setBackground(new java.awt.Color(55, 58, 64));
        jlblHomeIcon.setForeground(new java.awt.Color(255, 255, 255));
        jlblHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblHomeIcon.setText("\uf015");
        jlblHomeIcon.setOpaque(true);
        jpnlBarra.add(jlblHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 30, 50));

        jbtnPrimero.setBackground(new java.awt.Color(55, 58, 64));
        jbtnPrimero.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jbtnPrimero.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrimero.setText("    Primero");
        jbtnPrimero.setBorder(null);
        jbtnPrimero.setFocusable(false);
        jbtnPrimero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnPrimero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseMoved(evt);
            }
        });
        jbtnPrimero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnPrimeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnPrimeroFocusLost(evt);
            }
        });
        jbtnPrimero.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnPrimeroMouseWheelMoved(evt);
            }
        });
        jbtnPrimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseReleased(evt);
            }
        });
        jbtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrimeroActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 50));

        jbtnQuinto.setBackground(new java.awt.Color(20, 23, 31));
        jbtnQuinto.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnQuinto.setForeground(new java.awt.Color(205, 207, 208));
        jbtnQuinto.setText("    Quinto");
        jbtnQuinto.setBorder(null);
        jbtnQuinto.setFocusable(false);
        jbtnQuinto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnQuinto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseMoved(evt);
            }
        });
        jbtnQuinto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnQuintoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnQuintoFocusLost(evt);
            }
        });
        jbtnQuinto.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnQuintoMouseWheelMoved(evt);
            }
        });
        jbtnQuinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseReleased(evt);
            }
        });
        jbtnQuinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuintoActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnQuinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 130, 50));

        jbtnTercero.setBackground(new java.awt.Color(20, 23, 31));
        jbtnTercero.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnTercero.setForeground(new java.awt.Color(205, 207, 208));
        jbtnTercero.setText("    Tercero");
        jbtnTercero.setBorder(null);
        jbtnTercero.setFocusable(false);
        jbtnTercero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnTercero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseMoved(evt);
            }
        });
        jbtnTercero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseExited(evt);
            }
        });
        jbtnTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTerceroActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnTercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, 50));

        jbtnCuarto.setBackground(new java.awt.Color(20, 23, 31));
        jbtnCuarto.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnCuarto.setForeground(new java.awt.Color(205, 207, 208));
        jbtnCuarto.setText("    Cuarto");
        jbtnCuarto.setBorder(null);
        jbtnCuarto.setFocusable(false);
        jbtnCuarto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnCuarto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnCuartoMouseMoved(evt);
            }
        });
        jbtnCuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCuartoMouseExited(evt);
            }
        });
        jbtnCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuartoActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnCuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 50));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 101, 116));
        jLabel4.setText("Servimotos S.A.C");
        jpnlBarra.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        jLabel2.setBackground(new java.awt.Color(241, 240, 243));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 240, 243));
        jLabel2.setText("servimotos");
        jpnlBarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jbtnSegundo.setBackground(new java.awt.Color(20, 23, 31));
        jbtnSegundo.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnSegundo.setForeground(new java.awt.Color(205, 207, 208));
        jbtnSegundo.setText("    Segundo");
        jbtnSegundo.setBorder(null);
        jbtnSegundo.setFocusable(false);
        jbtnSegundo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnSegundo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnSegundoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnSegundoMouseMoved(evt);
            }
        });
        jbtnSegundo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnSegundoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnSegundoFocusLost(evt);
            }
        });
        jbtnSegundo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnSegundoMouseWheelMoved(evt);
            }
        });
        jbtnSegundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSegundoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnSegundoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnSegundoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnSegundoMouseReleased(evt);
            }
        });
        jbtnSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSegundoActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 50));

        jlblVentaIcon.setBackground(new java.awt.Color(20, 23, 31));
        jlblVentaIcon.setForeground(new java.awt.Color(205, 207, 208));
        jlblVentaIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblVentaIcon.setText("\uf788");
        jlblVentaIcon.setOpaque(true);
        jpnlBarra.add(jlblVentaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 30, 50));

        jlblRepuestosIcon.setBackground(new java.awt.Color(20, 23, 31));
        jlblRepuestosIcon.setForeground(new java.awt.Color(205, 207, 208));
        jlblRepuestosIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRepuestosIcon.setText("\uf1c0");
        jlblRepuestosIcon.setOpaque(true);
        jpnlBarra.add(jlblRepuestosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 30, 50));

        jlblReporteIcon.setBackground(new java.awt.Color(20, 23, 31));
        jlblReporteIcon.setForeground(new java.awt.Color(205, 207, 208));
        jlblReporteIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblReporteIcon.setText("\uf201");
        jlblReporteIcon.setOpaque(true);
        jpnlBarra.add(jlblReporteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 30, 50));

        jlblClientesIcon.setBackground(new java.awt.Color(20, 23, 31));
        jlblClientesIcon.setForeground(new java.awt.Color(205, 207, 208));
        jlblClientesIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblClientesIcon.setText("\uf007");
        jlblClientesIcon.setOpaque(true);
        jpnlBarra.add(jlblClientesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 30, 50));

        jlblNombreAdministrador.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jlblNombreAdministrador.setForeground(new java.awt.Color(181, 181, 186));
        jlblNombreAdministrador.setText("Administrador");
        jpnlBarra.add(jlblNombreAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 140, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(181, 181, 186));
        jLabel9.setText("MAIN MENU");
        jpnlBarra.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        getContentPane().add(jpnlBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 790));

        content.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 840, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPrimeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnPrimeroFocusGained
        
    }//GEN-LAST:event_jbtnPrimeroFocusGained

    private void jbtnPrimeroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseDragged

    }//GEN-LAST:event_jbtnPrimeroMouseDragged

    private void jbtnPrimeroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseMoved
        if (firstButton == false) {
            jbtnPrimero.setBackground(focus);
            jlblHomeIcon.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnPrimeroMouseMoved

    private void jbtnPrimeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnPrimeroFocusLost
        //
    }//GEN-LAST:event_jbtnPrimeroFocusLost

    private void jbtnPrimeroMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseWheelMoved
        
    }//GEN-LAST:event_jbtnPrimeroMouseWheelMoved

    private void jbtnPrimeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPrimeroMouseReleased

    private void jbtnPrimeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseExited
        if (firstButton == false) {
            jbtnPrimero.setBackground(base);
            jlblHomeIcon.setBackground(base);
        }
    }//GEN-LAST:event_jbtnPrimeroMouseExited

    private void jbtnTerceroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseMoved
        if (thirdButton == false) {
            jbtnTercero.setBackground(focus);
            jlblRepuestosIcon.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnTerceroMouseMoved

    private void jbtnTerceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseExited
        if (thirdButton == false) {
            jbtnTercero.setBackground(base);
            jlblRepuestosIcon.setBackground(base);
        }
    }//GEN-LAST:event_jbtnTerceroMouseExited

    private void jbtnCuartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCuartoMouseExited
        if (fourthButton == false) {
            jbtnCuarto.setBackground(base);
            jlblReporteIcon.setBackground(base);
        }
    }//GEN-LAST:event_jbtnCuartoMouseExited

    private void jbtnCuartoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCuartoMouseMoved
        if (fourthButton == false) {
            jbtnCuarto.setBackground(focus);
            jlblReporteIcon.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnCuartoMouseMoved

    private void jbtnQuintoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseDragged

    private void jbtnQuintoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseMoved
        if (fifthButton == false) {
            jbtnQuinto.setBackground(focus);
            jlblClientesIcon.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnQuintoMouseMoved

    private void jbtnQuintoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnQuintoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoFocusGained

    private void jbtnQuintoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnQuintoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoFocusLost

    private void jbtnQuintoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseWheelMoved

    private void jbtnQuintoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseExited
       if (fifthButton == false) {
            jbtnQuinto.setBackground(base);
            jlblClientesIcon.setBackground(base);
        }
    }//GEN-LAST:event_jbtnQuintoMouseExited

    private void jbtnQuintoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseReleased

    private void jbtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrimeroActionPerformed
        turnAllFalse();
        firstButton = true;
    }//GEN-LAST:event_jbtnPrimeroActionPerformed

    private void jbtnSegundoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSegundoMouseDragged

    private void jbtnSegundoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseMoved
        if (secondButton == false) {
            jbtnSegundo.setBackground(focus);
            jlblVentaIcon.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnSegundoMouseMoved
    
    private void jbtnSegundoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnSegundoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSegundoFocusGained

    private void jbtnSegundoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnSegundoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSegundoFocusLost

    private void jbtnSegundoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSegundoMouseWheelMoved

    private void jbtnSegundoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseExited
        if (secondButton == false) {
            jbtnSegundo.setBackground(base);
            jlblVentaIcon.setBackground(base);
        }
    }//GEN-LAST:event_jbtnSegundoMouseExited

    private void jbtnSegundoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSegundoMouseReleased

    private void jbtnSegundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMouseClicked
        //
    }//GEN-LAST:event_jbtnSegundoMouseClicked

    private void jbtnTerceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTerceroMouseClicked

    private void jbtnSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSegundoActionPerformed
        turnAllFalse();
        secondButton = true;
    }//GEN-LAST:event_jbtnSegundoActionPerformed

    private void jbtnTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTerceroActionPerformed
        turnAllFalse();
        thirdButton = true;
    }//GEN-LAST:event_jbtnTerceroActionPerformed

    private void jbtnCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuartoActionPerformed
        turnAllFalse();
        fourthButton = true;
    }//GEN-LAST:event_jbtnCuartoActionPerformed

    private void jbtnQuintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuintoActionPerformed
        turnAllFalse();
        fifthButton = true;
    }//GEN-LAST:event_jbtnQuintoActionPerformed

    private void jbtnPrimeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMousePressed
        
    }//GEN-LAST:event_jbtnPrimeroMousePressed

    private void jbtnSegundoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSegundoMousePressed
        
    }//GEN-LAST:event_jbtnSegundoMousePressed

    private void jbtnPrimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseClicked
        
    }//GEN-LAST:event_jbtnPrimeroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton jbtnCuarto;
    public javax.swing.JButton jbtnPrimero;
    public javax.swing.JButton jbtnQuinto;
    public javax.swing.JButton jbtnSegundo;
    public javax.swing.JButton jbtnTercero;
    public javax.swing.JLabel jlblClientesIcon;
    public javax.swing.JLabel jlblHomeIcon;
    public javax.swing.JLabel jlblNombreAdministrador;
    public javax.swing.JLabel jlblReporteIcon;
    public javax.swing.JLabel jlblRepuestosIcon;
    public javax.swing.JLabel jlblVentaIcon;
    private javax.swing.JPanel jpnlBarra;
    // End of variables declaration//GEN-END:variables
}
