package com.uni.thanosgym.view.routes;

import javax.swing.JPanel;
import javax.swing.JTextField;

import com.juancamr.route.Route;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import com.juancamr.components.Typography;
import com.uni.thanosgym.controllers.PlanController;
import com.uni.thanosgym.dao.CRUDPlan;

import com.uni.thanosgym.model.Plan;
import com.uni.thanosgym.model.Response;
import com.uni.thanosgym.utils.FrameUtils;
import com.uni.thanosgym.utils.Messages;

@Route("main:plan")
public class PanelPlan extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public PanelPlan() {
        initComponents();
        planesPanel.setLayout(null);
        refreshPlanes();
        FrameUtils.addOnClickEvent(jbtnCrear, this::createPlanEvent);
    }

    public void refreshPlanes() {
        planesPanel.removeAll();
        Response<Plan> plan = CRUDPlan.getInstance().getAll();
        List<Plan> listaPlanes = plan.getDataList();
        if ((listaPlanes).isEmpty()) {
            Typography noPlanes = new Typography();
            noPlanes.setBounds(0, 20, 200, 20);
            noPlanes.setText("No hay planes");
            planesPanel.add(noPlanes);
            return;
        }
        if (listaPlanes.size() >= 3) {
            jbtnCrear.setEnabled(false);
        }
        AtomicInteger index = new AtomicInteger();
        List<JPanel> planesInPanel = listaPlanes.stream().map(currentPlan -> {
            int width = 382;
            int height = 156;
            int i = index.getAndIncrement();
            JPanel panel = new JPanel();
            panel.setLayout(null);

            Typography planName = new Typography();
            planName.setType(Typography.Type.HEADING1);
            planName.setText(currentPlan.getName());
            planName.setBounds(20, 20, width, 40);

            Typography detail = new Typography();
            detail.setText(String.format("<html>S/ %.2f<br>Duración de %d días</html>", currentPlan.getPrice(),
                    currentPlan.getDurationDays()));
            detail.setBounds(20, 100, width, 40);

            panel.add(planName);
            panel.add(detail);

            panel.setBounds(0, 180 * i, width, height);
            return panel;
        }).collect(Collectors.toList());
        for (JPanel panel : planesInPanel) {
            planesPanel.add(panel);
        }
        planesPanel.revalidate();
        planesPanel.repaint();
    }

    public void createPlanEvent() {
        Map<String, String> req = new HashMap<>();
        req.put("name", jtxtNombre.getText());
        req.put("duration", jtxtDuracion.getText());
        req.put("price", jtxtPrecio.getText());
        if (Messages.confirm("¿Estás seguro de que deseas crear este plan?", "Crear plan")) {
            if (PlanController.createPlan(req)) {
                FrameUtils.clearInputs(new JTextField[] { jtxtNombre, jtxtDuracion, jtxtPrecio });
                refreshPlanes();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInterfaz = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        jPanel1 = new javax.swing.JPanel();
        typography2 = new com.juancamr.components.Typography();
        typography3 = new com.juancamr.components.Typography();
        jtxtNombre = new com.juancamr.components.InputComponent();
        jtxtDuracion = new com.juancamr.components.InputComponent();
        typography4 = new com.juancamr.components.Typography();
        typography5 = new com.juancamr.components.Typography();
        jtxtPrecio = new com.juancamr.components.InputComponent();
        jbtnCrear = new com.juancamr.components.ButtonComponent();
        planesPanel = new javax.swing.JPanel();

        jpnlInterfaz.setBackground(new java.awt.Color(255, 255, 255));
        jpnlInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlInterfazMouseClicked(evt);
            }
        });
        jpnlInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Planes");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING1);
        jpnlInterfaz.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography2.setText("Crear Plan");
        typography2.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        typography3.setText("Nombre del plan");
        jPanel1.add(typography3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, -1));
        jPanel1.add(jtxtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, -1));

        typography4.setText("Duración en días");
        jPanel1.add(typography4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        typography5.setText("Precio");
        jPanel1.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, -1));

        jbtnCrear.setText("Crear");
        jbtnCrear.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel1.add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 260, 40));

        jpnlInterfaz.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 338, 522));

        planesPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout planesPanelLayout = new javax.swing.GroupLayout(planesPanel);
        planesPanel.setLayout(planesPanelLayout);
        planesPanelLayout.setHorizontalGroup(
                planesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 380, Short.MAX_VALUE));
        planesPanelLayout.setVerticalGroup(
                planesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 550, Short.MAX_VALUE));

        jpnlInterfaz.add(planesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 380, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 840,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 690,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlInterfazMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jpnlInterfazMouseClicked

    }// GEN-LAST:event_jpnlInterfazMouseClicked

    private void buttonComponent1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonComponent1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonComponent1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.ButtonComponent jbtnCrear;
    private javax.swing.JPanel jpnlInterfaz;
    private com.juancamr.components.InputComponent jtxtDuracion;
    private com.juancamr.components.InputComponent jtxtNombre;
    private com.juancamr.components.InputComponent jtxtPrecio;
    private javax.swing.JPanel planesPanel;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography2;
    private com.juancamr.components.Typography typography3;
    private com.juancamr.components.Typography typography4;
    private com.juancamr.components.Typography typography5;
    // End of variables declaration//GEN-END:variables
}
