/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.routes;

import java.util.Map;

import javax.swing.text.JTextComponent;

import java.io.File;
import java.util.HashMap;

import com.juancamr.route.Route;
import com.uni.thanosgym.utils.Messages;
import com.juancamr.route.Router;
import com.uni.thanosgym.controllers.AuthController;
import com.uni.thanosgym.model.Response;
import com.uni.thanosgym.utils.FrameUtils;

/**
 *
 * @author jcmro
 */
@Route("auth:auth/register")
public class PanelRegister extends javax.swing.JPanel {

    public static File imageSelected = null;

    /**
     * Creates new form PanelRegister
     */
    public PanelRegister() {
        initComponents();
        FrameUtils.addOnClickEvent(jbtnUploadImagen, this::chooseImageEvent);
        FrameUtils.addOnClickEvent(jbtnRegistro, this::registerEvent);
        FrameUtils.addEnterEvent(jtxtRepeatPassword, this::registerEvent);
        FrameUtils.addOnClickEvent(jbtnInicioSesion, () -> {
            Router.getInstance().go("auth/login");
        });
    }

    private void registerEvent() {
        Map<String, Object> params = new HashMap<>();
        params.put("username", jtxtNombreUsuario.getText());
        params.put("password", new String(jPassword.getPassword()));
        params.put("fullname", jtxtNombresCompletos.getText());
        params.put("email", jtxtCorreo.getText());
        params.put("phone", jtxtPhone.getText());
        params.put("repeatPassword", new String(jtxtRepeatPassword.getPassword()));
        params.put("isForMaster", jCheckIsForMaster.isSelected());
        params.put("image", imageSelected);

        if (AuthController.register(params)) {
            FrameUtils.clearInputs(
                    new JTextComponent[] { jtxtCorreo, jtxtNombresCompletos, jtxtNombreUsuario, jtxtPhone, jPassword,
                            jtxtRepeatPassword });
        }
    }

    private void chooseImageEvent() {
        Response<File> response = FrameUtils.chooseImage(this);
        if (response.isSuccess()) {
            imageSelected = response.getData();
            jlblFileName.setText(imageSelected.getName());
        } else {
            Messages.show(response.getMessage());
            imageSelected = null;
            jlblFileName.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jlblExito = new javax.swing.JLabel();
        jCheckIsForMaster = new javax.swing.JCheckBox();
        typography1 = new com.juancamr.components.Typography();
        jlblFileName = new com.juancamr.components.Typography();
        jbtnUploadImagen = new com.juancamr.components.ButtonComponent();
        jbtnRegistro = new com.juancamr.components.ButtonComponent();
        jtxtNombresCompletos = new com.juancamr.components.InputComponent();
        jtxtCorreo = new com.juancamr.components.InputComponent();
        jtxtPhone = new com.juancamr.components.InputComponent();
        jtxtNombreUsuario = new com.juancamr.components.InputComponent();
        jPassword = new javax.swing.JPasswordField();
        jtxtRepeatPassword = new javax.swing.JPasswordField();
        jbtnInicioSesion = new com.juancamr.components.ButtonComponent();
        typography2 = new com.juancamr.components.Typography();
        typography3 = new com.juancamr.components.Typography();
        typography4 = new com.juancamr.components.Typography();
        typography5 = new com.juancamr.components.Typography();
        typography6 = new com.juancamr.components.Typography();
        typography7 = new com.juancamr.components.Typography();

        setPreferredSize(new java.awt.Dimension(420, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblExito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlblExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 310, 40));

        jCheckIsForMaster.setBackground(new java.awt.Color(255, 255, 255));
        jCheckIsForMaster.setText("Master");
        jPanel3.add(jCheckIsForMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        typography1.setText("Registro");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING1);
        jPanel3.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jlblFileName.setText("Imagen");
        jlblFileName.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(jlblFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));

        jbtnUploadImagen.setText("Foto");
        jbtnUploadImagen.setType(com.juancamr.components.ButtonComponent.Type.SMALL);
        jPanel3.add(jbtnUploadImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jbtnRegistro.setText("Registro");
        jbtnRegistro.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel3.add(jbtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 330, 40));
        jPanel3.add(jtxtNombresCompletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, -1));
        jPanel3.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, -1));
        jPanel3.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, -1));
        jPanel3.add(jtxtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 330, -1));
        jPanel3.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 330, -1));
        jPanel3.add(jtxtRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 330, -1));

        jbtnInicioSesion.setText("Iniciar sesión");
        jbtnInicioSesion.setType(com.juancamr.components.ButtonComponent.Type.SMALL);
        jPanel3.add(jbtnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        typography2.setText("Repetir Contraseña *");
        typography2.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        typography3.setText("Nombres *");
        typography3.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        typography4.setText("Correo *");
        typography4.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        typography5.setText("Celular");
        typography5.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        typography6.setText("Nombre de usuario *");
        typography6.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        typography7.setText("Contraseña *");
        typography7.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel3.add(typography7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnRegistroActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jbtnRegistroActionPerformed

    private void jtxtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtxtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtxtNombreUsuarioActionPerformed

    private void jtxtNombresCompletosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtxtNombresCompletosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtxtNombresCompletosActionPerformed

    private void jbtnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnInicioSesionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jbtnInicioSesionActionPerformed

    private void jtxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtxtCorreoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtxtCorreoActionPerformed

    private void jtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtxtPhoneActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtxtPhoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox jCheckIsForMaster;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private com.juancamr.components.ButtonComponent jbtnInicioSesion;
    private com.juancamr.components.ButtonComponent jbtnRegistro;
    private com.juancamr.components.ButtonComponent jbtnUploadImagen;
    public javax.swing.JLabel jlblExito;
    private com.juancamr.components.Typography jlblFileName;
    private com.juancamr.components.InputComponent jtxtCorreo;
    private com.juancamr.components.InputComponent jtxtNombreUsuario;
    private com.juancamr.components.InputComponent jtxtNombresCompletos;
    private com.juancamr.components.InputComponent jtxtPhone;
    private javax.swing.JPasswordField jtxtRepeatPassword;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography2;
    private com.juancamr.components.Typography typography3;
    private com.juancamr.components.Typography typography4;
    private com.juancamr.components.Typography typography5;
    private com.juancamr.components.Typography typography6;
    private com.juancamr.components.Typography typography7;
    // End of variables declaration//GEN-END:variables
}
