/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.routes;

import javax.swing.JPanel;
import com.juancamr.components.Typography;
import com.juancamr.route.Route;
import com.juancamr.route.RoutingUtils;

import java.awt.Color;
import java.util.List;

import com.uni.thanosgym.config.Theme;
import com.uni.thanosgym.controllers.ProveedorController;
import com.uni.thanosgym.dao.CRUDProveedor;
import com.uni.thanosgym.view.dialogs.AgregarProveedor;
import java.util.Map;
import java.util.stream.Collectors;

/**
 *
 * @author juancamr
 */
@Route("main:proveedor*")
public class PanelProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelProveedor
     */
    public PanelProveedor() {
        initComponents();
        jpnlProveedores.setLayout(new java.awt.GridLayout(3, 4, 20, 20));

        if (CRUDProveedor.getInstance().getAll().getDataList().isEmpty()) {
            Typography noProveedores = new Typography();
            noProveedores.setText("No hay proveedores registrados");
            jpnlProveedores.add(noProveedores);
            return;
        }
        refreshProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        jpnlProveedores = new javax.swing.JPanel();
        jbtnAgregar = new com.juancamr.components.ButtonComponent();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Proveedores");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING1);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jpnlProveedores.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jpnlProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 550));

        jbtnAgregar.setText("Agregar");
        jbtnAgregar.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jbtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
    }// </editor-fold>//GEN-END:initComponents
     //

    public void refreshProveedores() {
        jpnlProveedores.removeAll();

        List<JPanel> paneles = CRUDProveedor.getInstance().getAll().getDataList().stream()
                .map((prov) -> {
                    JPanel panel = new JPanel();
                    panel.setBackground(Theme.colors.grayCenizo);
                    panel.setLayout(null);

                    Typography nombre = new Typography();
                    nombre.setType(Typography.Type.HEADING2);
                    nombre.setText(prov.getNombre());
                    nombre.setBounds(10, 10, 140, 20);

                    panel.add(nombre);
                    return panel;
                }).collect(Collectors.toList());

        paneles.forEach((panel) -> {
            jpnlProveedores.add(panel);
        });

        jpnlProveedores.revalidate();
        jpnlProveedores.repaint();
    }

    private void jbtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jbtnAgregarMouseClicked
        Map<String, Object> params = RoutingUtils.openDialog(new AgregarProveedor());
        if (ProveedorController.registrar(params)) {
            refreshProveedores();
        }
    }// GEN-LAST:event_jbtnAgregarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.ButtonComponent jbtnAgregar;
    private javax.swing.JPanel jpnlProveedores;
    private com.juancamr.components.Typography typography1;
    // End of variables declaration//GEN-END:variables
}
