package com.uni.thanosgym.view;

import java.awt.Color;

public class MainWindow extends javax.swing.JFrame {
    
    Color base = new Color(20,23,31);
    Color focus = new Color(55, 58, 64);
    
    boolean firstButton = true;
    boolean secondButton = false;
    public boolean thirdButton = false;
    boolean fourthButton = false;
    public boolean fifthButton = false;
    
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(this);
        setSize(1060, 690);
    }
    
    public void turnAllFalse() {
        firstButton = false;
        secondButton = false;
        thirdButton = false;
        fourthButton = false;
        fifthButton = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBarra = new javax.swing.JPanel();
        jbtnPrimero = new javax.swing.JButton();
        jbtnQuinto = new javax.swing.JButton();
        jbtnTercero = new javax.swing.JButton();
        jbtnCuarto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnCliente = new javax.swing.JButton();
        jlblNombreAdministrador = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlBarra.setBackground(new java.awt.Color(20, 23, 31));
        jpnlBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrimero.setBackground(new java.awt.Color(55, 58, 64));
        jbtnPrimero.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jbtnPrimero.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrimero.setText("    Primero");
        jbtnPrimero.setBorder(null);
        jbtnPrimero.setFocusable(false);
        jbtnPrimero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnPrimero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseMoved(evt);
            }
        });
        jbtnPrimero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnPrimeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnPrimeroFocusLost(evt);
            }
        });
        jbtnPrimero.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnPrimeroMouseWheelMoved(evt);
            }
        });
        jbtnPrimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnPrimeroMouseReleased(evt);
            }
        });
        jbtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrimeroActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 50));

        jbtnQuinto.setBackground(new java.awt.Color(20, 23, 31));
        jbtnQuinto.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnQuinto.setForeground(new java.awt.Color(205, 207, 208));
        jbtnQuinto.setText("    Quinto");
        jbtnQuinto.setBorder(null);
        jbtnQuinto.setFocusable(false);
        jbtnQuinto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnQuinto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseMoved(evt);
            }
        });
        jbtnQuinto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnQuintoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnQuintoFocusLost(evt);
            }
        });
        jbtnQuinto.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnQuintoMouseWheelMoved(evt);
            }
        });
        jbtnQuinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnQuintoMouseReleased(evt);
            }
        });
        jbtnQuinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuintoActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnQuinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 130, 50));

        jbtnTercero.setBackground(new java.awt.Color(20, 23, 31));
        jbtnTercero.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnTercero.setForeground(new java.awt.Color(205, 207, 208));
        jbtnTercero.setText("    Tercero");
        jbtnTercero.setBorder(null);
        jbtnTercero.setFocusable(false);
        jbtnTercero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnTercero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseMoved(evt);
            }
        });
        jbtnTercero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnTerceroMouseExited(evt);
            }
        });
        jbtnTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTerceroActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnTercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, 50));

        jbtnCuarto.setBackground(new java.awt.Color(20, 23, 31));
        jbtnCuarto.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnCuarto.setForeground(new java.awt.Color(205, 207, 208));
        jbtnCuarto.setText("    Cuarto");
        jbtnCuarto.setBorder(null);
        jbtnCuarto.setFocusable(false);
        jbtnCuarto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnCuarto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnCuartoMouseMoved(evt);
            }
        });
        jbtnCuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCuartoMouseExited(evt);
            }
        });
        jbtnCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuartoActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnCuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 50));

        jLabel2.setBackground(new java.awt.Color(241, 240, 243));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 240, 243));
        jLabel2.setText("ThanosGym");
        jpnlBarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jbtnCliente.setBackground(new java.awt.Color(20, 23, 31));
        jbtnCliente.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jbtnCliente.setForeground(new java.awt.Color(205, 207, 208));
        jbtnCliente.setText("    Clientes");
        jbtnCliente.setBorder(null);
        jbtnCliente.setFocusable(false);
        jbtnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtnClienteMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnClienteMouseMoved(evt);
            }
        });
        jbtnCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbtnClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnClienteFocusLost(evt);
            }
        });
        jbtnCliente.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtnClienteMouseWheelMoved(evt);
            }
        });
        jbtnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnClienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnClienteMouseReleased(evt);
            }
        });
        jbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClienteActionPerformed(evt);
            }
        });
        jpnlBarra.add(jbtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 50));

        jlblNombreAdministrador.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jlblNombreAdministrador.setForeground(new java.awt.Color(181, 181, 186));
        jlblNombreAdministrador.setText("Administrador");
        jpnlBarra.add(jlblNombreAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 140, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(181, 181, 186));
        jLabel9.setText("MAIN MENU");
        jpnlBarra.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        getContentPane().add(jpnlBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 690));

        content.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 840, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPrimeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnPrimeroFocusGained
        
    }//GEN-LAST:event_jbtnPrimeroFocusGained

    private void jbtnPrimeroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseDragged

    }//GEN-LAST:event_jbtnPrimeroMouseDragged

    private void jbtnPrimeroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseMoved
        if (firstButton == false) {
            jbtnPrimero.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnPrimeroMouseMoved

    private void jbtnPrimeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnPrimeroFocusLost
        //
    }//GEN-LAST:event_jbtnPrimeroFocusLost

    private void jbtnPrimeroMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseWheelMoved
        
    }//GEN-LAST:event_jbtnPrimeroMouseWheelMoved

    private void jbtnPrimeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPrimeroMouseReleased

    private void jbtnPrimeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseExited
        if (firstButton == false) {
            jbtnPrimero.setBackground(base);
        }
    }//GEN-LAST:event_jbtnPrimeroMouseExited

    private void jbtnCuartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCuartoMouseExited
        if (fourthButton == false) {
            jbtnCuarto.setBackground(base);
        }
    }//GEN-LAST:event_jbtnCuartoMouseExited

    private void jbtnCuartoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCuartoMouseMoved
        if (fourthButton == false) {
            jbtnCuarto.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnCuartoMouseMoved

    private void jbtnQuintoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseDragged

    private void jbtnQuintoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseMoved
        if (fifthButton == false) {
            jbtnQuinto.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnQuintoMouseMoved

    private void jbtnQuintoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnQuintoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoFocusGained

    private void jbtnQuintoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnQuintoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoFocusLost

    private void jbtnQuintoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseWheelMoved

    private void jbtnQuintoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseExited
       if (fifthButton == false) {
            jbtnQuinto.setBackground(base);
        }
    }//GEN-LAST:event_jbtnQuintoMouseExited

    private void jbtnQuintoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnQuintoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuintoMouseReleased

    private void jbtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrimeroActionPerformed
        turnAllFalse();
        firstButton = true;
    }//GEN-LAST:event_jbtnPrimeroActionPerformed

    private void jbtnClienteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteMouseDragged

    private void jbtnClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMouseMoved
        if (secondButton == false) {
            jbtnCliente.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnClienteMouseMoved
    
    private void jbtnClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteFocusGained

    private void jbtnClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnClienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteFocusLost

    private void jbtnClienteMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtnClienteMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteMouseWheelMoved

    private void jbtnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMouseExited
        if (secondButton == false) {
            jbtnCliente.setBackground(base);
        }
    }//GEN-LAST:event_jbtnClienteMouseExited

    private void jbtnClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnClienteMouseReleased

    private void jbtnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMouseClicked
        //
    }//GEN-LAST:event_jbtnClienteMouseClicked

    private void jbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClienteActionPerformed
        turnAllFalse();
        secondButton = true;
    }//GEN-LAST:event_jbtnClienteActionPerformed

    private void jbtnCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuartoActionPerformed
        turnAllFalse();
        fourthButton = true;
    }//GEN-LAST:event_jbtnCuartoActionPerformed

    private void jbtnQuintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuintoActionPerformed
        turnAllFalse();
        fifthButton = true;
    }//GEN-LAST:event_jbtnQuintoActionPerformed

    private void jbtnPrimeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMousePressed
        
    }//GEN-LAST:event_jbtnPrimeroMousePressed

    private void jbtnClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClienteMousePressed
        
    }//GEN-LAST:event_jbtnClienteMousePressed

    private void jbtnPrimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrimeroMouseClicked
        
    }//GEN-LAST:event_jbtnPrimeroMouseClicked

    private void jbtnTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTerceroActionPerformed
        turnAllFalse();
        thirdButton = true;
    }//GEN-LAST:event_jbtnTerceroActionPerformed

    private void jbtnTerceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseExited
        if (thirdButton == false) {
            jbtnTercero.setBackground(base);
        }
    }//GEN-LAST:event_jbtnTerceroMouseExited

    private void jbtnTerceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTerceroMouseClicked

    private void jbtnTerceroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTerceroMouseMoved
        if (thirdButton == false) {
            jbtnTercero.setBackground(focus);
        }
    }//GEN-LAST:event_jbtnTerceroMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton jbtnCliente;
    public javax.swing.JButton jbtnCuarto;
    public javax.swing.JButton jbtnPrimero;
    public javax.swing.JButton jbtnQuinto;
    public javax.swing.JButton jbtnTercero;
    public javax.swing.JLabel jlblNombreAdministrador;
    private javax.swing.JPanel jpnlBarra;
    // End of variables declaration//GEN-END:variables
}
