/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view;

import com.uni.thanosgym.controller.ControladorUtilidad;
import com.uni.thanosgym.model.Utility;

/**
 *
 * @author juancamr
 */
public class PanelUtilidad extends javax.swing.JPanel {

    /**
     * Creates new form PanelUtility
     */
    public PanelUtilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnCrear = new javax.swing.JButton();
        jtxtBusquedaUtilidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUtilidad = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Busqueda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jbtnCrear.setText("Crear");
        jPanel1.add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 140, 40));

        jtxtBusquedaUtilidad.setBackground(new java.awt.Color(250, 250, 250));
        jtxtBusquedaUtilidad.setBorder(null);
        jPanel1.add(jtxtBusquedaUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 330, 40));

        jtblUtilidad.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jtblUtilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblUtilidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblUtilidad);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 630, 450));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void jtblUtilidadMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtblUtilidadMouseClicked
        int fila = jtblUtilidad.getSelectedRow();
        if (fila != -1) {
            int idUtilidad = Integer.parseInt(String.valueOf(jtblUtilidad.getValueAt(fila, 0)));
            String nombre = String.valueOf(jtblUtilidad.getValueAt(fila, 1));
            int cantidad = Integer.parseInt(String.valueOf(jtblUtilidad.getValueAt(fila, 2)));
            int peso = Integer.parseInt(String.valueOf(jtblUtilidad.getValueAt(fila, 3)));
            Utility producto = new Utility(idUtilidad, nombre, peso, cantidad);
            ControladorUtilidad.showOptions(producto);
        }
    }// GEN-LAST:event_jtblUtilidadMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnCrear;
    public javax.swing.JTable jtblUtilidad;
    public javax.swing.JTextField jtxtBusquedaUtilidad;
    // End of variables declaration//GEN-END:variables
}
