/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view;

/**
 *
 * @author jhere
 */
public class PanelClient extends javax.swing.JPanel {

    /**
     * Creates new form PanelClient
     */
    public PanelClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInterfaz = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxtDniClienteAgregar = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jlblExito = new javax.swing.JLabel();
        jtxtNombreClienteAgregar = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtDireccionClienteAdd = new javax.swing.JTextField();
        jtxtTelefonoClienteAdd = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jtxtDireccionCorreoAdd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcbxPlanRegistro = new javax.swing.JComboBox<>();
        jblLoading = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(840, 690));

        jpnlInterfaz.setBackground(new java.awt.Color(255, 255, 255));
        jpnlInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlInterfazMouseClicked(evt);
            }
        });
        jpnlInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 118));
        jLabel13.setText("DNI");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jtxtDniClienteAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDniClienteAgregar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDniClienteAgregar.setBorder(null);
        jtxtDniClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDniClienteAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDniClienteAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 20));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 118));
        jLabel14.setText("Nombres y Apellidos");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jbtnAgregar.setBackground(new java.awt.Color(20, 23, 31));
        jbtnAgregar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jbtnAgregar.setForeground(new java.awt.Color(241, 240, 243));
        jbtnAgregar.setText("AGREGAR");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 120, 40));

        jlblExito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlblExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 310, 40));

        jtxtNombreClienteAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtNombreClienteAgregar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtNombreClienteAgregar.setBorder(null);
        jtxtNombreClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreClienteAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtNombreClienteAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 10));

        jLabel23.setBackground(new java.awt.Color(105, 105, 118));
        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel23.setText("Registrar cliente");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(105, 105, 118));
        jLabel18.setText("Direccion");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 30));

        jtxtDireccionClienteAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDireccionClienteAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDireccionClienteAdd.setBorder(null);
        jtxtDireccionClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionClienteAddActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDireccionClienteAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 300, 30));

        jtxtTelefonoClienteAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtTelefonoClienteAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtTelefonoClienteAdd.setBorder(null);
        jtxtTelefonoClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefonoClienteAddActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTelefonoClienteAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 300, 30));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 300, 10));

        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 300, 10));

        jLabel28.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(105, 105, 118));
        jLabel28.setText("Telefono");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 30));

        jLabel29.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(105, 105, 118));
        jLabel29.setText("Plan");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, 30));

        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 10));

        jtxtDireccionCorreoAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDireccionCorreoAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtDireccionCorreoAdd.setBorder(null);
        jtxtDireccionCorreoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionCorreoAddActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtDireccionCorreoAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 300, 30));

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(105, 105, 118));
        jLabel19.setText("Correo");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        jPanel3.add(jcbxPlanRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 120, 30));
        jPanel3.add(jblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 160, 30));

        jpnlInterfaz.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDniClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDniClienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniClienteAgregarActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jtxtNombreClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreClienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreClienteAgregarActionPerformed

    private void jtxtDireccionClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionClienteAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionClienteAddActionPerformed

    private void jtxtTelefonoClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefonoClienteAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoClienteAddActionPerformed

    private void jtxtDireccionCorreoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionCorreoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionCorreoAddActionPerformed

    private void jpnlInterfazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlInterfazMouseClicked

    }//GEN-LAST:event_jpnlInterfazMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel jblLoading;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JComboBox<String> jcbxPlanRegistro;
    public javax.swing.JLabel jlblExito;
    private javax.swing.JPanel jpnlInterfaz;
    public javax.swing.JTextField jtxtDireccionClienteAdd;
    public javax.swing.JTextField jtxtDireccionCorreoAdd;
    public javax.swing.JTextField jtxtDniClienteAgregar;
    public javax.swing.JTextField jtxtNombreClienteAgregar;
    public javax.swing.JTextField jtxtTelefonoClienteAdd;
    // End of variables declaration//GEN-END:variables
}
