package com.uni.thanosgym.view.dialogs;

import java.util.Map;

import com.juancamr.route.DialogPanel;

/**
 *
 * @author juancamr
 */
public class AgregarProveedor extends DialogPanel {

    /**
     * Creates new form AgregarProveedor
     */
    public AgregarProveedor() {
        initComponents();
        setButtonAction(button);
        setOnAction((Map<String, Object> params) -> {
            params.put("nombre", jtxtNombre.getText());
            params.put("ruc", jtxtRUC.getText());
            params.put("phone", jtxtTelefono.getText());
            params.put("address", jtxtDireccion.getText());
            return params;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        jtxtNombre = new com.juancamr.components.InputComponent();
        typography2 = new com.juancamr.components.Typography();
        button = new com.juancamr.components.ButtonComponent();
        jtxtRUC = new com.juancamr.components.InputComponent();
        jtxtTelefono = new com.juancamr.components.InputComponent();
        typography4 = new com.juancamr.components.Typography();
        typography5 = new com.juancamr.components.Typography();
        jtxtDireccion = new com.juancamr.components.InputComponent();
        typography6 = new com.juancamr.components.Typography();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Agregar proveedor");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 310, -1));

        typography2.setText("Nombre");
        typography2.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        button.setText("Agregar");
        button.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 310, 40));

        jtxtRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRUCActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 310, -1));
        jPanel1.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        typography4.setText("Teléfono");
        typography4.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        typography5.setText("RUC");
        typography5.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel1.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 310, -1));

        typography6.setText("Dirección");
        typography6.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRUCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.juancamr.components.ButtonComponent button;
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.InputComponent jtxtDireccion;
    private com.juancamr.components.InputComponent jtxtNombre;
    private com.juancamr.components.InputComponent jtxtRUC;
    private com.juancamr.components.InputComponent jtxtTelefono;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography2;
    private com.juancamr.components.Typography typography4;
    private com.juancamr.components.Typography typography5;
    private com.juancamr.components.Typography typography6;
    // End of variables declaration//GEN-END:variables
}
