/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.juancamr.route.DialogPanel;

/**
 *
 * @author juancamr
 */
public class AgregarStockProducto extends DialogPanel{

    /**
     * Creates new form AgregarStockProducto
     */
    public AgregarStockProducto() {
        initComponents();
        setButtonAction(button);
        setOnAction(params -> {
            params.put("cantidad", jtxtCantidad.getText());
            params.put("fecha", dateChooser.getDate());
            params.put("precio", jtxtPrecio.getText());
            return params;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        button = new com.juancamr.components.ButtonComponent();
        jtxtPrecio = new com.juancamr.components.InputComponent();
        jtxtCantidad = new com.juancamr.components.InputComponent();
        typography4 = new com.juancamr.components.Typography();
        typography5 = new com.juancamr.components.Typography();
        dateChooser = new com.toedter.calendar.JDateChooser();
        typography6 = new com.juancamr.components.Typography();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Agregar stock");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        button.setText("Agregar");
        button.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 40));

        jtxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, -1));
        jPanel1.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, -1));

        typography4.setText("Cantidad");
        typography4.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        typography5.setText("Fecha de vencimiento");
        typography5.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, -1));

        typography6.setText("Precio");
        typography6.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.juancamr.components.ButtonComponent button;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.InputComponent jtxtCantidad;
    private com.juancamr.components.InputComponent jtxtPrecio;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography4;
    private com.juancamr.components.Typography typography5;
    private com.juancamr.components.Typography typography6;
    // End of variables declaration//GEN-END:variables
}
