/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.juancamr.route.DialogPanel;
import com.uni.thanosgym.dao.CRUDProveedor;
import com.uni.thanosgym.model.Proveedor;
import com.uni.thanosgym.model.Response;
import com.uni.thanosgym.utils.FrameUtils;
import com.uni.thanosgym.utils.Messages;

import java.io.File;
import java.util.Map;

/**
 *
 * @author juancamr
 */
public class AgregarUtilidad extends DialogPanel {

    private File imageSelected = null;

    /**
     * Creates new form AgregarUtilidad
     */
    public AgregarUtilidad() {
        initComponents();
        setButtonAction(button);

        setOnAction((Map<String, Object> params) -> {
            params.put("nombre", jtxtNombre.getText());
            params.put("peso", jtxtPeso.getText());
            params.put("cantidad", jtxtPeso.getText());
            params.put("image", imageSelected);
            params.put("proveedor_id", ((ComboItem) jcbxProveedores.getSelectedItem()).getId());
            return params;
        });

        Response<Proveedor> resProv = CRUDProveedor.getInstance().getAll();
        for (Proveedor proveedor : resProv.getDataList()) {
            jcbxProveedores.addItem(new ComboItem(proveedor.getId(), proveedor.getNombre()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        jtxtNombre = new com.juancamr.components.InputComponent();
        typography2 = new com.juancamr.components.Typography();
        button = new com.juancamr.components.ButtonComponent();
        typography3 = new com.juancamr.components.Typography();
        jtxtPeso = new com.juancamr.components.InputComponent();
        jtxtCantidad = new com.juancamr.components.InputComponent();
        typography4 = new com.juancamr.components.Typography();
        jcbxProveedores = new javax.swing.JComboBox<>();
        typography5 = new com.juancamr.components.Typography();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Agregar utilidad");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 310, -1));

        typography2.setText("Nombre");
        typography2.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        button.setText("Agregar");
        button.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 310, 40));

        typography3.setText("Proveedor");
        typography3.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jtxtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));
        jPanel1.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 140, -1));

        typography4.setText("Cantidad");
        typography4.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jPanel1.add(jcbxProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        typography5.setText("Peso");
        typography5.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPesoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtxtPesoActionPerformed
    }// GEN-LAST:event_jtxtPesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.juancamr.components.ButtonComponent button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<ComboItem> jcbxProveedores;
    private com.juancamr.components.InputComponent jtxtCantidad;
    private com.juancamr.components.InputComponent jtxtNombre;
    private com.juancamr.components.InputComponent jtxtPeso;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography2;
    private com.juancamr.components.Typography typography3;
    private com.juancamr.components.Typography typography4;
    private com.juancamr.components.Typography typography5;
    // End of variables declaration//GEN-END:variables
    //
    public static class ComboItem {
        private int id;
        private String name;

        public ComboItem(int id, String name) {
            this.id = id;
            this.name = name;
        }

        public int getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        @Override
        public String toString() {
            return name;
        }
    }

}
