/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.juancamr.route.DialogPanel;
import java.util.Map;

/**
 *
 * @author juancamr
 */
public class Congelar extends DialogPanel {

    /**
     * Creates new form Congelar
     */
    public Congelar() {
        initComponents();
        setButtonAction(button);
        setOnAction((params) -> {
            params.put("dias", jtxtCantidadDias.getText());
            return params;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        button = new com.juancamr.components.ButtonComponent();
        typography5 = new com.juancamr.components.Typography();
        typography6 = new com.juancamr.components.Typography();
        jtxtCantidadDias = new com.juancamr.components.InputComponent();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Agregar producto");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        button.setText("Agregar");
        button.setType(com.juancamr.components.ButtonComponent.Type.PRIMARY);
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 310, 40));

        typography5.setBackground(new java.awt.Color(204, 0, 51));
        typography5.setForeground(new java.awt.Color(204, 0, 0));
        typography5.setText("Recuerda que solo puedes congelar hasta 3 veces");
        typography5.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        typography6.setText("Cantidad de días");
        typography6.setType(com.juancamr.components.Typography.Type.MEDIUM);
        jPanel1.add(typography6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(jtxtCantidadDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.juancamr.components.ButtonComponent button;
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.InputComponent jtxtCantidadDias;
    private com.juancamr.components.Typography typography1;
    private com.juancamr.components.Typography typography5;
    private com.juancamr.components.Typography typography6;
    // End of variables declaration//GEN-END:variables
}
