/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.uni.thanosgym.model.Contrato;
import com.uni.thanosgym.utils.StringUtils;

import java.util.Date;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author juancamr
 */
public class ListaContratos extends javax.swing.JFrame {
    private List<Contrato> contratos;

    /**
     * Creates new form ListaContratos
     */
    public ListaContratos(List<Contrato> contratos) {
        initComponents();
        this.contratos = contratos;

        contratos.forEach((contrato) -> {
            // "Fecha de emisión", "Fecha de vencimiento", "Membresía", "Estado"
            String estado = contrato.getEstado();
            String[] datos = new String[] { StringUtils.parseSpanishDate(contrato.getCreatedAt()),
                    StringUtils.parseSpanishDate(contrato.getSubscriptionUntil()), contrato.getPlan().getName(),
                    estado };
            ((javax.swing.table.DefaultTableModel) jtblContratos.getModel()).addRow(datos);
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        e = new javax.swing.JScrollPane();
        jtblContratos = new javax.swing.JTable();
        typography1 = new com.juancamr.components.Typography();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblContratos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Fecha de emisión", "Fecha de vencimiento", "Membresía", "Estado"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jtblContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblContratosMouseClicked(evt);
            }
        });
        e.setViewportView(jtblContratos);

        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 720, 480));

        typography1.setText("Contratos");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 874,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblContratosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtblContratosMouseClicked
        int index = jtblContratos.getSelectedRow();
        if (index != -1) {
            Contrato contrato = contratos.get(index);
            new ContratoData(contrato);
        }
    }// GEN-LAST:event_jtblContratosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane e;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jtblContratos;
    private com.juancamr.components.Typography typography1;
    // End of variables declaration//GEN-END:variables
}
