/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.uni.thanosgym.model.Asistencia;
import com.uni.thanosgym.utils.StringUtils;
import javax.swing.JFrame;

import java.util.List;

/**
 *
 * @author juancamr
 */
public class ListaAsistencias extends javax.swing.JFrame {

    /**
     * Creates new form ListaAsistencias
     */
    public ListaAsistencias(List<Asistencia> asistencias) {
        initComponents();

        for (Asistencia asistencia : asistencias) {
            String[] row = new String[]{String.valueOf(asistencia.getId()), asistencia.getCliente().getFullName(), StringUtils.parseSpanishDate(asistencia.getIngreso())};
            ((javax.swing.table.DefaultTableModel) jtblAsistencias.getModel()).addRow(row);
        }

        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typography2 = new com.juancamr.components.Typography();
        jPanel1 = new javax.swing.JPanel();
        e = new javax.swing.JScrollPane();
        jtblAsistencias = new javax.swing.JTable();
        jlblCliente = new com.juancamr.components.Typography();

        typography2.setText("Asistencias para ");
        typography2.setType(com.juancamr.components.Typography.Type.HEADING2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblAsistenciasMouseClicked(evt);
            }
        });
        e.setViewportView(jtblAsistencias);

        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 530, 480));

        jlblCliente.setText("Asistencias");
        jlblCliente.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(jlblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblAsistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAsistenciasMouseClicked
        int index = jtblAsistencias.getSelectedRow();
        if (index != -1) {
        }
    }//GEN-LAST:event_jtblAsistenciasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane e;
    private javax.swing.JPanel jPanel1;
    private com.juancamr.components.Typography jlblCliente;
    private javax.swing.JTable jtblAsistencias;
    private com.juancamr.components.Typography typography2;
    // End of variables declaration//GEN-END:variables
}
