/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uni.thanosgym.view.dialogs;

import com.uni.thanosgym.model.Notification;
import com.uni.thanosgym.utils.FrameUtils;

import java.util.List;

/**
 *
 * @author juancamr
 */
public class Notificaciones extends javax.swing.JFrame {
    private List<Notification> notificaciones;

    /**
     * Creates new form Notificaciones
     */
    public Notificaciones(List<Notification> notificaciones) {
        initComponents();
        this.notificaciones = notificaciones;
        for (Notification notificacion : notificaciones) {
            String[] datos = new String[]{
                notificacion.getDescripcion()
            };
            ((javax.swing.table.DefaultTableModel) jtblNotificaciones.getModel()).addRow(datos);
        }
        FrameUtils.setupWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        typography1 = new com.juancamr.components.Typography();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNotificaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typography1.setText("Notificaciones");
        typography1.setType(com.juancamr.components.Typography.Type.HEADING2);
        jPanel1.add(typography1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jtblNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblNotificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblNotificacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblNotificaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 380, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblNotificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblNotificacionesMouseClicked
        int row = jtblNotificaciones.getSelectedRow();
        if (row == -1) {
            return;
        }

        Notification notificacion = notificaciones.get(row);
        notificacion.getAction().run();
        dispose();
    }//GEN-LAST:event_jtblNotificacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblNotificaciones;
    private com.juancamr.components.Typography typography1;
    // End of variables declaration//GEN-END:variables
}
