package com.uni.thanosgym.view.dialogs;

import java.util.Map;

import com.juancamr.route.DialogPanel;
import com.uni.thanosgym.utils.FrameUtils;

/**
 *
 * @author juancamr
 */
public class VerificacionMaster extends DialogPanel {

    /**
     * Creates new form VerificacionMaster
     */
    public VerificacionMaster() {
        initComponents();
        setButtonAction(button);
        setOnAction((Map<String, Object> params) -> {
            params.put("username", input.getText());
            params.put("password", String.valueOf(passwordInput.getPassword()));
            return params;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button.setText("Verificar");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 230, 30));
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JTextField input;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordInput;
    // End of variables declaration//GEN-END:variables
}
