/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.thanosgym.view.layouts;

import com.juancamr.route.Layout;
import com.juancamr.route.LayoutPanel;
import com.uni.thanosgym.utils.FrameUtils;

/**
 *
 * @author juancamr
 */
@Layout("auth")
public class SessionLayout extends LayoutPanel {

    /**
     * Creates new form MainLayout
     */
    public SessionLayout() {
        initComponents();
        setContent(content);
        String image = "https://t3.ftcdn.net/jpg/06/08/15/96/360_F_608159635_oQ0NJZIj1XCGlSaptlc0m1g0jb5M1SL8.jpg";
        FrameUtils.renderImageFromWeb(image, jlblImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jlblImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 690));

        jlblImage.setText("image");
        jPanel1.add(jlblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 630, 690));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 690));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblImage;
    // End of variables declaration//GEN-END:variables
}
